### PR TITLE
License service improvements

### PR DESCRIPTION
**Pull request by sunilk747**
- [x] Filter and rectify incorrect splitting of licenses.
- [x] Add proper error message for various cases of unknown licenses.
- [x] Add any unknown or missing license.

### CODE REVIEW

**Comment by sunilk747** [comment]
[test]

**Comment by ravsa** [comment]
[test]

**Comment by sunilk747** [comment]
[test]

**Comment by sunilk747** [comment]
[test]

**Comment by sunilk747** [comment]
[test]

**Comment by sunilk747** [comment]
[test]

**Pull request merged**
