### PR TITLE
[MRG -1] Fix CI unit test run

### PR DESCRIPTION
**Pull request by rootAvish**
Need to install GCC on Centos-CI, re-add the missing requirements and voila!

### CODE REVIEW

**Comment by abs51295** [comment]
I think it should work now ;) 🎉

**Comment by tisnik** [comment]
@rootAvish do you want to merge just the fix, or the auth code? I think that the auth.code (+utils etc. etc.) would need more work (unit tests etc.). Probably better to split this PR?

**Comment by rootAvish** [comment]
@tisnik I don't want to get this merged, that's why I added the [MRG -1] 🙂 I've kept it up for @sunilk747 to look over and continue working on, if the build changes are required independent of #80 as well I can open a separate PR otherwise @sunilk747 can incorporate them as a part of #80 itself since the discussions around the code have all happened in that thread.

**Comment by tisnik** [comment]
cool, thank you @rootAvish

**Comment by rootAvish** [comment]
Closing in favor of #80 being merged.

**Pull request closed without merging**
