### PR TITLE
change license API resposne

### PR DESCRIPTION
**Pull request by sunilk747**

### CODE REVIEW

**Comment by ravsa** [comment]
let's wait for the build to finish

**Comment by miteshvp** [comment]
@sunilk747 with the change in response, and addition of new endpoint, it will be good if you can update the README as well.

**Comment by ravsa** [comment]
@miteshvp It was a bug, distinct licenses showing multiple times.

**Comment by miteshvp** [comment]
@ravsa, we did change the response due to dep-editor work. And with the addition of new endpoint, it needs to be updated in README as well. And of course, there are no unit-tests to support this use-case. @sunilk747 please make sure all these things are handled

**Comment by sunilk747** [comment]
@miteshvp Yes. Currently working on adding the unit test for the added endpoints

**Pull request merged**
